# docker-compose.yml

services:
  webapp:
    container_name: personal-finance-app
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      # This is your existing volume for hot-reloading code
      - ./finance_tracker:/app/finance_tracker
      # --- THIS LINE IS CRITICAL ---
      # This syncs the migrations folder between your Mac and the container
      - ./migrations:/app/migrations