"""Add link between recurring and standard transactions

Revision ID: 94726f174ce2
Revises: 38488a328bfd
Create Date: 2025-06-14 15:23:25.625325

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94726f174ce2"
down_revision = "38488a328bfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("recurring_transaction_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            None, "recurring_transaction", ["recurring_transaction_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transaction", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("recurring_transaction_id")

    # ### end Alembic commands ###
