"""Add affects_balance flag to Transaction model

Revision ID: ac831458beb3
Revises: 7b5d3db8f1b7
Create Date: 2025-06-17 09:57:33.857443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac831458beb3'
down_revision = '7b5d3db8f1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affects_balance', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('affects_balance')

    # ### end Alembic commands ###
