"""-m

Revision ID: f56aa0bc81f6
Revises: f8792a9996b2
Create Date: 2025-06-13 12:15:45.564271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56aa0bc81f6'
down_revision = 'f8792a9996b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_processed_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.drop_column('last_processed_date')

    # ### end Alembic commands ###
