# .github/workflows/ci.yml

name: CI/CD - Build, Push to GHCR, and Deploy to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permission for GITHUB_TOKEN to write packages
    
    outputs:
      # This job outputs the full image name with the specific SHA tag
      image_tag: ${{ steps.docker_build.outputs.image_id }}
      # And the lowercase owner name for the next job
      owner_lc: ${{ steps.repo_owner_lc.outputs.name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository owner to lowercase
        id: repo_owner_lc
        run: echo "name=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.repo_owner_lc.outputs.name }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the secure, automatic token for pushing

      - name: Build, tag, and push Docker image
        id: docker_build
        run: |
          # The image name must be all lowercase
          IMAGE_NAME="ghcr.io/${{ steps.repo_owner_lc.outputs.name }}/personal-finance-webapp"
          # The tag will be the unique git commit SHA
          IMAGE_TAG="${IMAGE_NAME}:${{ github.sha }}"
          
          docker build -t ${IMAGE_TAG} .
          docker push ${IMAGE_TAG}
          
          # Set the full image name as a job output
          echo "image_id=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # This job depends on the image being successfully built

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for infrastructure file changes
        id: path_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'infra/**'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # This step ONLY runs IF infrastructure files changed
      - name: Deploy Infrastructure Changes with Terraform
        if: steps.path_filter.outputs.infra == 'true'
        run: |
          echo "Infrastructure changes detected. Running terraform apply..."
          cd infra
          terraform init
          terraform apply -auto-approve \
            -var="docker_image_to_deploy=${{ needs.build-and-push.outputs.image_tag }}" \
            -var="github_username=${{ needs.build-and-push.outputs.owner_lc }}" \
            -var="db_admin_login=${{ secrets.DB_ADMIN_LOGIN }}" \
            -var="db_admin_password=${{ secrets.DB_ADMIN_PASSWORD }}" \
            -var="github_pat=${{ secrets.GHCR_PAT }}"
            
      # This step ONLY runs IF NO infrastructure files changed
      - name: Deploy Application Update with Azure CLI
        if: steps.path_filter.outputs.infra != 'true'
        run: |
          echo "No infrastructure changes. Using fast app deployment..."
          az containerapp update \
            --name pfa-webapp \
            --resource-group personal-finance-app-rg \
            --image ${{ needs.build-and-push.outputs.image_tag }}