# .github/workflows/ci.yml

name: CI/CD - Build, Push, and Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Build and Push Docker Image ---
  build-and-push:
    runs-on: ubuntu-latest
    # We no longer need special permissions here because we will use our PAT.
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository owner to lowercase
        id: repo_owner_lc
        run: echo "name=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # --- THIS STEP IS NOW CHANGED ---
      - name: Log in to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.repo_owner_lc.outputs.name }}
          # Use the GHCR_PAT secret for a consistent identity
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo_owner_lc.outputs.name }}/personal-finance-webapp

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # --- JOB 2: Deploy to Azure Container Apps ---
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra
      - name: Terraform Apply
        env:
          TF_VAR_db_admin_login: ${{ secrets.DB_ADMIN_LOGIN }}
          TF_VAR_db_admin_password: ${{ secrets.DB_ADMIN_PASSWORD }}
          TF_VAR_github_pat: ${{ secrets.GHCR_PAT }} # This part remains the same
          TF_VAR_github_username: ${{ github.repository_owner }}
        run: terraform apply -auto-approve
        working-directory: ./infra