# .github/workflows/ci.yml

name: CI/CD - Build, Push, and Deploy Application

# --- TRIGGER ---
# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# --- JOBS ---
jobs:
  # --- JOB 1: Build and Push Docker Image ---
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # --- JOB 2: Deploy to Azure Container Apps ---
  deploy:
    runs-on: ubuntu-latest
    # This job will only start after the 'build-and-push' job has succeeded
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          # Use the JSON credentials stored in the GitHub secret
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          # This prevents a wrapper script from being used, which can be
          # helpful for compatibility with different Terraform commands.
          terraform_wrapper: false
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra # Run the command in the 'infra' directory

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra # Run the command in the 'infra' directory