# .github/workflows/ci.yml

name: CI/CD - Build, Push, and Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW STEP TO FIX CASING ---
      - name: Set repository name to lowercase
        id: repo_name
        # This step uses the 'tr' command to convert the repository name (e.g., PrajwalMadhyastha/personal-finance-webapp)
        # to all lowercase and sets it as an output variable for other steps to use.
        run: echo "name=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Use the new, lowercased repository name from the previous step's output
          images: ghcr.io/${{ steps.repo_name.outputs.name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
        working-directory: ./infra
      - name: Terraform Apply
        env:
          TF_VAR_db_admin_login: ${{ secrets.DB_ADMIN_LOGIN }}
          TF_VAR_db_admin_password: ${{ secrets.DB_ADMIN_PASSWORD }}
          TF_VAR_github_pat: ${{ secrets.GHCR_PAT }}
          # Use the lowercased repository owner name from the GitHub context
          TF_VAR_github_username: ${{ steps.repo_name.outputs.name }}
        run: terraform apply -auto-approve
        working-directory: ./infra