# .github/workflows/ci.yml

name: CI/CD - Build, Push, and Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    outputs:
      image_tag: ${{ steps.docker_build.outputs.image_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR Name from Terraform
        id: tf-out
        # This step needs terraform, so we add the setup step here too
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform for Outputs
        run: terraform init
        working-directory: ./infra

      - name: Get ACR Details
        id: acr-details
        run: |
          cd infra
          ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)
          echo "acr_login_server=$ACR_LOGIN_SERVER" >> $GITHUB_OUTPUT
          ACR_NAME=$(terraform output -raw acr_name)
          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
      
      - name: Log in to Azure Container Registry
        run: az acr login --name ${{ steps.acr-details.outputs.acr_name }}
        
      - name: Build and Push Docker Image to ACR
        id: docker_build
        run: |
          IMAGE_TAG="${{ steps.acr-details.outputs.acr_login_server }}/personal-finance-webapp:${{ github.sha }}"
          docker build -t ${IMAGE_TAG} .
          docker push ${IMAGE_TAG}
          echo "image_id=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for infrastructure file changes
        id: path_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'infra/**'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # --- THIS IS THE MISSING STEP THAT HAS BEEN ADDED BACK ---
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        if: steps.path_filter.outputs.infra == 'true' # Only setup terraform if needed

      # --- This step now has the setup before it ---
      - name: Deploy Infrastructure Changes with Terraform
        if: steps.path_filter.outputs.infra == 'true'
        run: |
          echo "Infrastructure changes detected. Running terraform apply..."
          cd infra
          terraform init
          terraform apply -auto-approve \
            -var="docker_image_to_deploy=${{ needs.build-and-push.outputs.image_tag }}" \
            -var="db_admin_login=${{ secrets.DB_ADMIN_LOGIN }}" \
            -var="db_admin_password=${{ secrets.DB_ADMIN_PASSWORD }}"
            
      - name: Deploy Application Update with Azure CLI
        if: steps.path_filter.outputs.infra != 'true'
        run: |
          echo "No infrastructure changes. Using fast app deployment..."
          az containerapp update \
            --name pfa-webapp \
            --resource-group personal-finance-app-rg \
            --image ${{ needs.build-and-push.outputs.image_tag }}