# .github/workflows/ci.yml

name: CI/CD - Build, Push, and Deploy Application

on:
  push:
    branches: [ "main" ]

jobs:

  # =======================================================
  # JOB 1: Run the test suite
  # =======================================================
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use the same version as your Dockerfile

      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Run Tests with Pytest'
        run: pytest
  # =======================================================
  # JOB 1: Build the Docker image and push it to GHCR
  # =======================================================
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write # Permission for GITHUB_TOKEN to write packages
    
    outputs:
      image_tag: ${{ steps.docker_build.outputs.image_id }}
      owner_lc: ${{ steps.repo_owner_lc.outputs.name }}

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Set repository owner to lowercase'
        id: repo_owner_lc
        run: echo "name=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.repo_owner_lc.outputs.name }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 'Build and Push Docker Image'
        id: docker_build
        run: |
          LOWERCASE_REPO_NAME=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${{ steps.repo_owner_lc.outputs.name }}/${LOWERCASE_REPO_NAME}"
          # The tag is the unique git commit SHA, which is a best practice
          IMAGE_TAG="${IMAGE_NAME}:${{ github.sha }}"
          
          echo "Building and pushing: ${IMAGE_TAG}"
          docker build -t ${IMAGE_TAG} .
          docker push ${IMAGE_TAG}
          
          # Set the full image name as a job output for the next job
          echo "image_id=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  # =======================================================
  # JOB 2: Deploy to Azure with Conditional Logic
  # =======================================================
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Depends on the build job

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Check for infrastructure file changes'
        id: path_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'infra/**'

      - name: 'Log in to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Setup Terraform'
        # This step ONLY runs IF infrastructure files changed
        if: steps.path_filter.outputs.infra == 'true'
        uses: hashicorp/setup-terraform@v2
        
      - name: 'Deploy Infrastructure Changes with Terraform'
        # This step ONLY runs IF infrastructure files changed
        if: steps.path_filter.outputs.infra == 'true'
        env:
          TF_VAR_db_admin_login: ${{ secrets.DB_ADMIN_LOGIN }}
          TF_VAR_db_admin_password: ${{ secrets.DB_ADMIN_PASSWORD }}
          TF_VAR_github_pat: ${{ secrets.GHCR_PAT }}
          TF_VAR_github_username: ${{ needs.build-and-push.outputs.owner_lc }}
          TF_VAR_flask_secret_key: ${{ secrets.FLASK_SECRET_KEY }}
          TF_VAR_task_secret_key: ${{ secrets.RECURRING_JOB_SECRET }}
        run: |
          echo "Infrastructure changes detected. Running terraform apply..."
          cd infra
          terraform init
          terraform apply -auto-approve -var="docker_image_to_deploy=${{ needs.build-and-push.outputs.image_tag }}"
            
      - name: 'Deploy Application Update with Azure CLI'
        # This step ONLY runs IF NO infrastructure files changed
        if: steps.path_filter.outputs.infra != 'true'
        run: |
          echo "No infrastructure changes. Using fast app deployment..."
          az containerapp update \
            --name pfa-webapp \
            --resource-group personal-finance-app-rg \
            --image ${{ needs.build-and-push.outputs.image_tag }}